### ISSUE TITLE
Causing Facebook login to fail

### ISSUE THREAD

**Issue by ninjz** [letsroundup/react-native-localytics#1]
After adding this component, my facebook login hangs after successfully logging in, and stays in the browser window.

```
(localytics) -[LLUploaderBase beginUploadWithApplicationKey:installId:libraryVersion:customerId:shouldUpdateHighWaterMark:]:
 + Abandoning upload. No data given.
```

is what is logged in my console when I complete the login, i think is causing the issue

**Comment by dozoisch** [comment]
Hmm that's weird. Just to make sure, have you initialize the sdk properly as of Localytics getting started documentation? You need to use

```
  NSString* localyticsKey = @"yourkey";
  [Localytics autoIntegrate:localyticsKey launchOptions:launchOptions];
```

in your AppDelegate.m

---

Sorry for not answering earlier, completely missed that!

**Comment by dozoisch** [comment]
@ninjz Can't really help without more information!

**Comment by dozoisch** [comment]
I will close this issue for now. If you have more info, ping me and I'll reopen.
